FROM php:8.1.1-fpm

WORKDIR /var/www

RUN apt-get update

RUN apt-get install -y libzip-dev libpng-dev git zip curl
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libxslt-dev libicu-dev libmcrypt-dev libpng-dev libwebp-dev libxml2-dev

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp
RUN docker-php-ext-install gd mysqli pdo pdo_mysql sockets

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data
